wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    code_path: code/train_cls.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1681248847.639457
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 3
      - 13
      - 16
      - 23
      4: 3.8.5
      5: 0.13.6
      8:
      - 5
antithetic:
  desc: null
  value: true
batch_size:
  desc: null
  value: 64
data_name:
  desc: null
  value: scan
decay_rate:
  desc: null
  value: 0.0001
device:
  desc: null
  value: cuda:0
epoch:
  desc: null
  value: 2000
gpu:
  desc: null
  value: '0'
hidden:
  desc: null
  value: 512
kernel:
  desc: null
  value: true
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: vn_transformer_cls
n_knn:
  desc: null
  value: 20
name:
  desc: null
  value: '4090'
normal:
  desc: null
  value: false
num_class:
  desc: null
  value: 15
num_features:
  desc: null
  value: 512
num_heads:
  desc: null
  value: 16
num_layers:
  desc: null
  value: 4
num_point:
  desc: null
  value: 512
num_random:
  desc: null
  value: 20
num_votes:
  desc: null
  value: 3
optimizer:
  desc: null
  value: AdamW
pooling:
  desc: null
  value: mean
restore:
  desc: null
  value: null
rot:
  desc: null
  value: aligned
save_dir:
  desc: null
  value: /mnt/c/users/sssak/desktop/models/VNPerformer
